---
title: "Homework 03: Probability"
output: html_document
---

Due date: 2017-02-10

1. The airline company FlyMoar claims that of regularly scheduled flighs, departures and arrivals are on time `r round(runif(1, 0.7, 0.9), 2)*100`\% and `r round(runif(1, 0.75, 0.88), 2)*100`\% of the time, respectively.   The probability that a flight arrives and departs on time is `r round(runif(1, 0.65, 0.75), 2)*100`\%. <!--- % PS Ex 2.33; 85%, 82%, and 78%, respectively --->

a. What is the probability that one of FlyMoar's flights arrived on time given that it departed on time?
b. What is the probability that one of FlyMoar's flights departed on time given that it arrived on time?

2. After randomly assigning 60 guinea pigs to receive one of three dose levels of vitamin C (0.5, 1, and 2 mg/day) by one of two supplements, orange juice (OJ) or ascorbic acid (a form of vitamin C encoded as ‘VC’), researchers recorded the length of odontoblasts (cells responsible for tooth growth).

   a. Is this an experiment or an observational study?  Explain.
   b. State why the following plot shows that on average OJ causes higher odontoblast length than does VB.
   ```{r, fig.width=5, fig.height=3.5, fig.align="center", echo=FALSE}
   suppressMessages(library(tidyverse))
   qplot(factor(dose), len, data=ToothGrowth, geom="boxplot", colour=supp)
   ```
   c. Provide the R code to reproduce the plot above in full.  Hints: see examples from ?ggplot2::qplot; and ?datasets::ToothGrowth
   d. Justify my use of the word *causes* in part b.

3. Refer to the Systems Reliability section of the slides [ProbabilityExamples](https://roualdes.us/teaching/math314/lectures/probability_examples_handout.pdf).  Suppose the sequential system happens before the parallel system, such that the output of the sequential system is the input to the parallel system.  What is the probability of failure of this new complete system? The individual components have probabilities of success and failure independent of each other, as follows.


   Event        A       B       C       D       E       F
   ------       ---     ---     ---     ---     ---     ---
   success      0.9     0.85    0.8     0.1     0.15    0.2
   failure      0.1     0.15    0.2     0.9     0.85    0.8