---
title: "Homework 05: Likelihood and Sampling Distribution"
output: html_document
---

Due date: 2017-03-03

1. Derive the maximum likelihood estimator for the mean $\mu$ of the normal distribution.

2. Write an R function that replicates the applet we played with in class:  [http://onlinestatbook.com/stat_sim/sampling_dist/](http://onlinestatbook.com/stat_sim/sampling_dist/).  Your function could, but doesn't have to,

  **input**:

  `rng` -- (function) a function that generates a random sample of size `n` from a distribution of your choice, and returns a standardized (z-score associated with the) sample mean.

  `n` -- (integer) sample size

  `R` -- (integer) number of replicates

  **output**:

  a histogram of the `R` standardized sample means

a. How does the histogram change as you increase the sample size?  Try at least three different sample sizes, and provide plots for each.
b. Repeat with a different distribution function.  This could simply mean develop a second function that generates a random mean, similar to `rng` above, that uses a different distribution function.
c. Describe the sampling distribution from the new distribution function.