---
title: "Homework 10: Bootstrap"
output: html_document
---

Due date: 2017-04-24

1. Start from your work in HW 09.  Turn in all the necessary R code for the following.

a. Calculate the fitted/predicted values of your ANOVA model.  Explain, in one sentence, why there are so many of the same values.
b. Calculate the coefficients from your model.  Explain what the intercept is and you find another level's group mean.
c. Calculate the residuals for your model.  Pick a negative one and pick a positive one, explain what the sign of each means.

2. Pick a combination of two variables, that I haven't previously used, from my website or from an R package, calculate a 98% bootstrapped confidence interval of the correlation coefficient.  Provide at least

a. A description of the data -- the variables, the origin of the data and the data set (such that I could find it and replicate your work).
b. An appropriate plot to display the data with respect to your analysis.
c. A formal conclusion in both Statistics and in English.
d. The R code used to produce the analysis.
