---
title: "Homework 05"
output: html_document
---

Due date: 2016-10-21

Turn in numerical and R code answers in a knitted R Markdown file.  Some general hints: the R library dplyr will be quite helpful throughout this assignmnet, and is therefore encouraged; the Examples section of helpfiles a great way to learn R.

1. Using our data set named [email](https://roualdes.us/data/email.csv)

    a. calculate and interpret a 95% confidence interval for the mean number of line breaks in emails.
    b. formally test to see if the mean number of line breaks in emails is equal to $250$, use $\alpha=0.05$.
    c. does your confidence interval match the conclusion from your hypothesis test?
    d. what does the confidence interval tell you that the hypothesis test does not?
    e. create a new variable that takes on the value 1 whenever an email has more than one line break and a zero otherwise.
    f. calculate and interpret a $90$\% confidence interval for the variable you just created.


2. A 95% confidence interval for a population mean is given as (18.985, 21.015).  This confidence interval is based on a simple random sample of 36 observations. Calculate the sample mean and standard deviation.  Use the t-distribution in any calculations.


3. Air quality measurements were collected in a random sample of 25 country capitals in 2013, and then again in the same cities in 2014. We would like to use these data to compare average air quality between the two years.

    a. Should we use a one-sided or a two-sided test? Explain your reasoning.
    b. Should we use a paired or non-paired test? Explain your reasoning.
    c. Should we use a t-test or a z-test? Explain your reasoning.

4. Use the dataset datasets::ToothGrowth, which come pre-installed in R.

    a. ?ToothGrowth
    b. Make one plot that uses all three variables from the dataset -- no bar charts.  Hint: you can coercea numeric variable to a factor if the variable has a relatively small amount of levels; try specifying the colour [sic] argument in qplot.
    c. Calculate 98% confidence intervals of len at each level of supp and dose.
    d. Write a short paragraph explaining your results.

5. Use the dataset ape::carnivora -- if you haven't installed the library ape yet, you will need to.

    a. Run library(ape) and then ?carnivora
    b. Choose a numeric variable of you choice and calculate 90% confidence intervals for each family in the dataset.  Hint: ?mean for help on avoiding NAs.
    c. Write a short paragraph explaining your results.
    d. Make a scatter plot of your variable by Family.
    e. Add means in blue and error bars in red to your plot using stat_summary.  Hint: look for fun.y=mean for means and fun.data=mean_se for error bars.
