---
title: "Homework 08: more t-test"
output: html_document
---

Due date: 2017-04-03

Turn in R code and numerical answers for the following.

1. Using the dataset [carnivora](https://roualdes.us/data/carnivora.csv) complete a full analysis of a numerical variable of your choice, broken up by the categorical variable `SuperFamily`.  Please limit your write up to 1 page.  A complete analysis contains at least

    a. A summary of the dataset (since you don't otherwise know anything about these data, make it up) and the variables to be analyzed.
    b. An appropriate plot for the data.
    c. A few summary statistics -- generaly sample size, mean, median, standard deviation.
    d. A description of the skew of the data based on the plot and summary statistics, and how this might affect your application of the Central Limit Theorem.
    e. If hypothesis testing, a formal set up of your hypotheses.
    f. An statistical test appropriate to your data.
    g. A statistical conclusion of your test.
    h. A conclusion that your Grandmother could understand.


Hints:

Use the following code chunk options to resize your plot

` ```{r, fig.width=3, fig.height=3, fig.align="center"} `

` # R code here `

` ``` `

```{r, eval=FALSE}
?t.test                                 # Formula interface?
```
