---
title: "Homework 06: Likelihood (again)"
output: html_document
---

Due date: 2017-03-10

1. Showing your work, derive the maximum likelihood estimator for $\alpha of the gamma distribution, with probability density function

   \[ f(x|\alpha,\beta) = \frac{\beta^{\alpha}}{\Gamma(\alpha)}x^{\alpha-1} \exp{(-\beta x)} \]

2. Copy the following code to generate a sample of random variables from $\Gamma(3, 5)$.  Use `optim` to estimate the shape $\alpha$ and rate $\beta$ from the data `x`.

```{r}
set.seed(20170305)
x <- rgamma(107, 3, 5)
```

3. Use your estimates from 2. to estimate the mean of the data `x`.

4. Use the function `mean` to estimate the mean of the data `x`.

5. Name one application of the Gamma distribution and explain why this distribution is well suited to this application, better than say the Exponential distribution.

6. Plot an approximate sampling distribution for the sample variance for the gamma distribution above.  Make three separate, reasonably sized plots, one for each sample size $n \in \{10, 25, 100\}$.

7. Referencing your data in 6., provide estimates of the population variance and standard error of the sample variance from your randomly generated data for each sample size.  Explain why the population variance does not change, but the standard error shrinks, as your sample size $n$ increases.